name: AWS Lambda Zip Deploy - Python
author: cmd-not-found
description: Zip deploy to AWS Lambda with requirements in a separate layer.
inputs:
  lambda_function_name:
    description: The Lambda function name. Check the AWS docs/readme for examples.
    required: true
  lambda_region:
    description: The AWS region. defaults to 'us-east-1'
    required: true
    default: us-east-1
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.lambda_function_name }}
    - ${{ inputs.lambda_region }}
branding:
  icon: 'cloud-lightning'
  color: 'white'